# Generated by Django 3.0.5 on 2020-11-15 20:59

import data.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('language', models.CharField(max_length=100, verbose_name='Язык')),
                ('code', models.CharField(max_length=30, verbose_name='Код языка')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('count', models.IntegerField(default=1, verbose_name='Число видео в месяц')),
            ],
        ),
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('ttf_normal', models.FileField(default='', upload_to=data.models.changeNormalName, verbose_name='Файл шрифта обычный')),
                ('ttf_bold', models.FileField(default='', upload_to=data.models.changeBoldName, verbose_name='Файл шрифта жирный')),
                ('ttf_italic', models.FileField(default='', upload_to=data.models.changeItalicName, verbose_name='Файл шрифта наклон')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
